### ISSUE TITLE
Data mining script

### ISSUE THREAD

**Issue by geekix** [ilyasozkurt/mobilephone-brands-and-models#1]
Hi,

By any chance, would you share the data mining script you used to get the datas ?

Thanks

**Comment by ilyasozkurt** [comment]
Hello @geekix,

Unfortunately, I could not find them. I think already delete them. 

Sorry to say that.

**Comment by geekix** [comment]
Thank you for taking the time to search =)

**Comment by ilyasozkurt** [comment]
Hello @geekix,

This week, I'm going to publish an update about this.

**Comment by geekix** [comment]
Nice ! thank you, I'm looking forward to see that =)

**Comment by ilyasozkurt** [comment]
@geekix Data updated :)

**Comment by geekix** [comment]
Great, thank you ! I will tell you if I have questions =)
