### ISSUE TITLE
problem

### ISSUE THREAD

**Issue by Aikanairo** [ilyasozkurt/mobilephone-brands-and-models#11]
the procedure is blocked at 4800 records, how can I read the errors? or the reason for the block? can i restart it from the breakpoint?

**Comment by Aikanairo** [comment]
i think it was the gsmarena server that was blocking the requests. imports stopped at 4800 items. is there a solution? I read on the internet that there are services like scraperapi.com that bypass the limitations.


forgive my ignorance, I approached scraping out of pure curiosity, I ran your script and was happy to see it working, too bad it crashed

**Comment by ilyasozkurt** [comment]
It's a protection that they're running. You can continue from the point that you are stuck. You just need to restart from another day, or you can slow down the requests with sleep(1); etc.

**Comment by Aikanairo** [comment]
To restart from the point of interruption, just send the command? The settings like sleep etc where can I change them Thanks again for your patience

**Comment by ilyasozkurt** [comment]
It's enough to run the same command from the point you stay. You're welcome

**Comment by Aikanairo** [comment]
I decided to start the procedure directly from my pc so I can eventually change the ip so as to avoid the block

I noticed that running the script this starts from 53% how can I make it start from 0?
