### ISSUE TITLE
file hash

### ISSUE THREAD

**Issue by Aikanairo** [ilyasozkurt/mobilephone-brands-and-models#12]
I made 2 scrapes, it always gets stuck at 10630 items more or less the same as those of your scrape that took place in 2021. how can I scrape the others too?

**Comment by Aikanairo** [comment]
I noticed that the count of the progress bar does not correspond to the number of devices entered in the db. when in cmd it counts 1823 devices, in the db there are 695 for a total of 32523 devices, I wonder: is it possible that when it reaches 10635 devices in the db the progression bar in cmd reaches 100% stopping in fact at the devices of the year 2021

**Comment by ilyasozkurt** [comment]
Just edit last_index.txt file and add +1 to last index to bypass it
