### ISSUE TITLE
autoload.php seems to be missing

### ISSUE THREAD

**Issue by odessa-paige-turner** [ilyasozkurt/mobilephone-brands-and-models#13]
When trying to run the re-scrape command, I get

`PHP Warning:  require(/<install_directory>/mobilephone-brands-and-models/scrapper/vendor/autoload.php): Failed to open stream: No such file or directory in /<install_directory>mobilephone-brands-and-models/scrapper/artisan on line 18`

The `vendor` directory `autoload.php` file seem to missing from the code base.

**Comment by ilyasozkurt** [comment]
Hello,

just run the command "composer install"
