### ISSUE TITLE
Terms of Service Violation?

### ISSUE THREAD

**Issue by deerawj** [ilyasozkurt/mobilephone-brands-and-models#15]
I am also trying to scrape gsmarena.com, when I noticed that their Terms of Service asked not to modify the information. I was wondering if using this data (or scraping the data) is allowed? 

> You may download, view, copy and print documents and graphics incorporated in these documents (the "Documents") from this website subject to the following: (1) the Documents may be used solely for personal, informational, non-commercial purposes; and (2) the **Documents may not be modified or altered in any way**. Except as expressly provided herein, you may not use, download, upload, copy, print, display, perform, reproduce, publish, license, post, transmit or distribute any information from this website in whole or in part without the prior written permission of GSMArena.com.

**Comment by ilyasozkurt** [comment]
Hello @deerawj,

If you ask about scraping any webmaster, they would say it's illegal. But, there is no difference between copying one by one or scraping that information and creating a database with that information. This method is also used by ChatGPT, etc., nowadays.

If they want to share this data like me, they could share it with JSON or SQL formatted. But they do not want to do it. So I did it. So, I do not accept it's illegal or any shit license rule.
