### ISSUE TITLE
Missing Information

### ISSUE THREAD

**Issue by Ro-Den** [ilyasozkurt/mobilephone-brands-and-models#5]
Some information is missing (JSON as example):

E.g.: [Huawei Mate 40 Pro+](https://www.gsmarena.com/huawei_mate_40_pro+-10550.php)

1. `Display Type` ("OLED, HDR10, 90Hz"). Due to conflict with `Battery Type`.
2. `Memory` unnamed ("SFS 1.0").  Due to conflict with `Sound` unnamed.
3. `Main Camera Features` ("Leica optics, LED flash, panorama, HDR"). Due to conflict with `Selfie Camera Features`.
4. `Main Camera Video` ("4K@30/60fps, 1080p@30/60/120/240/480fps, 720p@960fps, 720p@3840fps, HDR, gyro-EIS"). Due to conflict with `Selfie Camera Video`.

Also, it is wrong to use [Main Camera] "Penta" & [Selfie Camera] "Dual" as JSON keys. I think it's necessary to add two additional nested JSONs "main_camera" & "selfie_camera" with the following structure:

`"main_camera": {"Main_Camera_Type":"Penta","Main_Camera_Specifications":"50 MP, f/1.9, 23mm (wide), 1/1.28", 1.22µm, omnidirectional PDAF, Laser AF, OIS
12 MP, f/2.4, (telephoto), PDAF, OIS, 3x optical zoom
8 MP, f/4.4, 240mm (periscope telephoto), PDAF, OIS, 10x optical zoom
20 MP, f/2.4, 14mm (ultrawide), PDAF
TOF 3D, (depth)","Main_Camera_Features":"Leica optics, LED flash, panorama, HDR","Main_Camera_Video":"4K@30/60fps, 1080p@30/60/120/240/480fps, 720p@960fps, 720p@3840fps, HDR, gyro-EIS"},"selfie_camera": {"Selfie_Camera_Type":"Dual","Selfie_Camera_Specifications":"13 MP, f/2.4, 18mm (ultrawide)
TOF 3D, (depth/biometrics sensor)","Selfie_Camera_Features":"HDR, panorama","Selfie_Camera_Video":"4K@30/60fps, 1080p@30/60/240fps"},`

**Comment by ilyasozkurt** [comment]
Hello @Ro-Den,

Thank you for your feedback. If there is missing data, you can re-scrape data yourself by using the scraper script.

Have nice day!

**Comment by Ro-Den** [comment]
There's no point in re-scraping, because the issue is in the scraper:

`$ttl = $row->find('.ttl')[0]->plaintext ?? null;`

It overwrites the data when the keys have the same name. Just check the above mentioned page source.

I hope that the following would work correctly:

`$ttl = $row->find('.ttl')[0]->data-spec ?? null;`

 Could you check it?
