### ISSUE TITLE
Non-Unique DB Keys in Scrapper

### ISSUE THREAD

**Issue by Ro-Den** [ilyasozkurt/mobilephone-brands-and-models#6]
Non-unique database keys being used in the `ScrapeCommand.php`:

`$ttl = $row->find('.ttl')[0]->plaintext ?? null;`

It resulted in some information have been overwritten (previously mentioned here: #5).

I hope that the following should work correctly:

`$ttl = $row->find('.ttl')[0]->data-spec ?? null;`

Please, check and re-scrape.

**Comment by ilyasozkurt** [comment]
Hello,

I will check and test it ASAP.

Thank you for your feedback!

**Comment by ilyasozkurt** [comment]
Hello,

I changed the data structure to solve the problem. 

Here's the new data structure, specs are arrays now, multi-line features are array items.

https://prnt.sc/32tt4zT78OZn

Have nice day!
